version: '3'

services:
  user:
    build: 
      context: user-microservice
    container_name: user-microservice
    working_dir: /app
    networks: 
      - node-network
    tty: true
    ports: 
      - "6001:6001"
    command: npm start

  admin:
    build: 
      context: admin-microservice
    container_name: admin-microservice
    working_dir: /app
    networks: 
      - node-network
    tty: true
    ports: 
      - "6002:6002"
    command: npm start

  seller:
    build: 
      context: seller-microservice
    container_name: seller-microservice
    working_dir: /app
    networks: 
      - node-network
    tty: true
    ports: 
      - "6003:6003"
    command: npm start

  customer:
    build: 
      context: customer-microservice
    container_name: customer-microservice
    working_dir: /app
    networks: 
      - node-network
    tty: true
    ports: 
      - "6004:6004"
    command: npm start

  cart:
    build: 
      context: cart-microservice
    container_name: cart-microservice
    working_dir: /app
    networks: 
      - node-network
    tty: true
    ports: 
      - "6005:6005"
    command: npm start

  order:
    build: 
      context: order-microservice
    container_name: order-microservice
    working_dir: /app
    networks: 
      - node-network
    tty: true
    ports: 
      - "6006:6006"
    command: npm start

  payment:
    build: 
      context: payment-microservice
    container_name: payment-microservice
    working_dir: /app
    networks: 
      - node-network
    tty: true
    ports: 
      - "6007:6007"
    command: npm start

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8080:8080"
    networks: 
      - node-network
    depends_on:
       - user
       - admin
       - seller
       - customer
       - order
       - cart
       - payment
  
networks: 
  node-network:
    driver: bridge
