version: "3"
services:

  customer:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: customer-microservice
    ports:
      - "6004:6004"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  