version: "3"
services:

  seller:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: seller-microservice
    ports:
      - "6003:6003"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  