version: "3"
services:

  seller-ms:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: seller-ms
    ports:
      - "5005:5005"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  