version: "3"
services:

  payment:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: payment-microservice
    ports:
      - "6007:6007"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  