version: "3"
services:

  admin-ms:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: admin-ms
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  