version: "3"
services:

  admin:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: admin-microservice
    ports:
      - "6002:6002"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  