version: "3"
services:

  order:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: order-microservice
    ports:
      - "6006:6006"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  