version: "3"
services:

  cart:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: cart-microservice
    ports:
      - "6005:6005"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  